### ISSUE TITLE
TypeError after Tailwind v2.0.1

### ISSUE THREAD

**Issue by FerasAloudah** [20lives/tailwindcss-rtl#10]
### Description
I keep receiving a TypeError when using this plugin, and I think it's because Tailwind has recently dropped support for IE11.

### Stack Trace
```
TypeError: target is not a function
    at generators (\node_modules\tailwindcss-rtl\src\paddingUtilities.js:4:3)
    at module.exports (\node_modules\tailwindcss-rtl\src\paddingUtilities.js:18:20)
    at \node_modules\tailwindcss-rtl\src\index.js:16:16
    at \node_modules\tailwindcss\lib\util\processPlugins.js:69:5
    at Array.forEach (<anonymous>)
    at _default (\node_modules\tailwindcss\lib\util\processPlugins.js:63:11)
    at \node_modules\tailwindcss\lib\processTailwindFeatures.js:60:54
    at LazyResult.runOnRoot (\node_modules\postcss\lib\lazy-result.js:276:16)
    at LazyResult.runAsync (\node_modules\postcss\lib\lazy-result.js:328:26)
    at LazyResult.async (\node_modules\postcss\lib\lazy-result.js:178:30)
```

**Comment by 20lives** [comment]
Expect an update soon.

**Comment by Ayman97** [comment]
Waiting for the update too :)

**Comment by 20lives** [comment]
Try latest version 6.0.1, should solve it.

**Comment by 20lives** [comment]
I can confim this works on both 1.9.6 and 2.0.1, if you have an issue please reopen.
